### ISSUE TITLE
Unable to set multiple constant voltages. Getting AttributeError: 'RuntimeError' object has no attribute 'message'

### ISSUE THREAD

**Issue by michael-zelos** [analogdevicesinc/m1k-fw#25]
Hi all,

I am trying to set a constant voltage at different time intervals. I am running the following code:
```
def main():
    session = Session()
    dev = session.devices[0]

    chan_a = dev.channels["A"]
    chan_b = dev.channels["B"]

    chan_a.mode = Mode.SVMI
    chan_b.mode = Mode.SVMI

    chan_a.constant(1.0)

    time.sleep(5)

    chan_a.constant(1.75)

    time.sleep(5)

    chan_a.constant(3.9)

    time.sleep(5)
```
However I keep receiving the following error:

Traceback (most recent call last):
  File "pysmu/libsmu.pyx", line 640, in pysmu.libsmu.SessionDevice.write
RuntimeError: data write timeout, no available queue space: Resource busy

During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "read-write.py", line 18, in <module>
    chan_a.constant(1.75)
  File "pysmu/libsmu.pyx", line 891, in pysmu.libsmu.Channel.constant
  File "pysmu/libsmu.pyx", line 794, in pysmu.libsmu.Channel.write
  File "pysmu/libsmu.pyx", line 646, in pysmu.libsmu.SessionDevice.write
AttributeError: 'RuntimeError' object has no attribute 'message'
```
I am using the examples as my template for creating this, but always get this same error every time. It seems like I need to flush the buffer or do a read, but even when attempting that it isn't working. Can you explain the reason for this or how I should be flushing the buffers if that is the issue?

**Comment by michael-zelos** [comment]
This is also the case for current mode as well.
